
services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      # - .:/app
      - /app/node_modules
      # - ./opt:/app/opt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    